<?php

declare(strict_types=1);

namespace Aether\AOT;

use Aether\Attributes\Inject;
use Aether\Attributes\Persistent;
use Aether\Attributes\Ephemeral;
use Aether\Container\ServiceScope;

/**
 * Hydrator Generator — AOT compilation for dependency injection.
 *
 * Scans classes for #[Inject], #[Persistent], #[Ephemeral] attributes
 * and generates static "hydrator" factory functions. This eliminates
 * all Reflection API usage at runtime — the container simply calls
 * the pre-compiled factory to instantiate a class.
 *
 * @package Aether\AOT
 */
final class HydratorGenerator
{
    /**
     * Generate hydrators for all classes in a directory.
     *
     * @param string $directory Source directory
     * @param string $namespace Base namespace
     * @param string $outputPath Output PHP file
     */
    public function generate(string $directory, string $namespace, string $outputPath): void
    {
        $classes = $this->discoverClasses($directory, $namespace);
        $hydrators = [];
        $bindings = [];

        foreach ($classes as $className) {
            if (!class_exists($className)) {
                continue;
            }

            $ref = new \ReflectionClass($className);
            if ($ref->isAbstract() || $ref->isInterface()) {
                continue;
            }

            $scope = $this->detectScope($ref);
            $deps = $this->extractDependencies($ref);

            $hydrators[$className] = [
                'scope' => $scope->value,
                'dependencies' => $deps,
            ];

            $bindings[] = [
                'id' => $className,
                'scope' => $scope,
                'dependencies' => $deps,
            ];
        }

        $this->writeHydratorFile($hydrators, $outputPath);
    }

    /**
     * Generate a single hydrator entry for a class.
     *
     * @return array{scope: string, dependencies: array<string, string>}
     */
    public function analyzeClass(string $className): array
    {
        $ref = new \ReflectionClass($className);
        return [
            'scope' => $this->detectScope($ref)->value,
            'dependencies' => $this->extractDependencies($ref),
        ];
    }

    /**
     * Detect the service scope from class attributes.
     */
    private function detectScope(\ReflectionClass $ref): ServiceScope
    {
        if (count($ref->getAttributes(Persistent::class)) > 0) {
            return ServiceScope::Persistent;
        }
        if (count($ref->getAttributes(Ephemeral::class)) > 0) {
            return ServiceScope::Ephemeral;
        }
        return ServiceScope::Transient;
    }

    /**
     * Extract constructor dependencies via #[Inject] or type hints.
     *
     * @return array<string, string> Parameter name => service ID
     */
    private function extractDependencies(\ReflectionClass $ref): array
    {
        $deps = [];
        $constructor = $ref->getConstructor();
        if ($constructor === null) {
            return $deps;
        }

        foreach ($constructor->getParameters() as $param) {
            // Check for explicit #[Inject] attribute
            $injectAttrs = $param->getAttributes(Inject::class);
            if (count($injectAttrs) > 0) {
                $inject = $injectAttrs[0]->newInstance();
                if ($inject->id !== '') {
                    $deps[$param->getName()] = $inject->id;
                    continue;
                }
            }

            // Fall back to type hint
            $type = $param->getType();
            if ($type instanceof \ReflectionNamedType && !$type->isBuiltin()) {
                $deps[$param->getName()] = $type->getName();
            }
        }

        return $deps;
    }

    /**
     * Write the compiled hydrator file.
     *
     * @param array<string, array{scope: string, dependencies: array<string, string>}> $hydrators
     */
    private function writeHydratorFile(array $hydrators, string $outputPath): void
    {
        $lines = [];
        $lines[] = "<?php";
        $lines[] = "";
        $lines[] = "declare(strict_types=1);";
        $lines[] = "";
        $lines[] = "/**";
        $lines[] = " * AUTO-GENERATED by Aether AOT Hydrator Generator.";
        $lines[] = " * DO NOT EDIT — regenerate with `php bin/aether aot:compile`.";
        $lines[] = " *";
        $lines[] = " * Generated: " . date('Y-m-d H:i:s');
        $lines[] = " * Classes: " . count($hydrators);
        $lines[] = " */";
        $lines[] = "";
        $lines[] = "use Aether\\Container\\Container;";
        $lines[] = "use Aether\\Container\\ServiceScope;";
        $lines[] = "";
        $lines[] = "return static function (Container \$c): void {";

        foreach ($hydrators as $className => $info) {
            $scope = match ($info['scope']) {
                'persistent' => 'ServiceScope::Persistent',
                'ephemeral' => 'ServiceScope::Ephemeral',
                default => 'ServiceScope::Transient',
            };

            if (count($info['dependencies']) === 0) {
                $lines[] = "    \$c->bind('{$className}', static fn() => new \\{$className}(), {$scope});";
            } else {
                $args = [];
                foreach ($info['dependencies'] as $param => $depId) {
                    $args[] = "\$c->resolve('{$depId}')";
                }
                $argStr = implode(', ', $args);
                $lines[] = "    \$c->bind('{$className}', static fn(Container \$c) => new \\{$className}({$argStr}), {$scope});";
            }
        }

        $lines[] = "};";
        $lines[] = "";

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($outputPath, implode("\n", $lines), LOCK_EX);
    }

    /**
     * @return array<string>
     */
    private function discoverClasses(string $directory, string $namespace): array
    {
        $classes = [];
        $files = $this->findPhpFiles($directory);

        foreach ($files as $file) {
            $baseDir = rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
            if (strncmp($file, $baseDir, strlen($baseDir)) !== 0) {
                continue;
            }
            $relative = substr($file, strlen($baseDir));
            if (str_ends_with($relative, '.php')) {
                $relative = substr($relative, 0, -4);
            }
            $classes[] = $namespace . '\\' . str_replace(DIRECTORY_SEPARATOR, '\\', $relative);
        }

        return $classes;
    }

    /** @return array<string> */
    private function findPhpFiles(string $dir): array
    {
        $files = [];
        $items = scandir($dir);
        if ($items === false) return $files;
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') continue;
            $path = $dir . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) {
                $files = array_merge($files, $this->findPhpFiles($path));
            } elseif (str_ends_with($item, '.php')) {
                $files[] = $path;
            }
        }
        return $files;
    }
}
