<?php

declare(strict_types=1);

namespace Aether\Router;

/**
 * Route Compiler — AOT compilation of the Radix Tree.
 *
 * Generates a static PHP file containing the entire route tree
 * as a nested array. This allows the JIT compiler to optimize
 * the lookup path into machine code on subsequent boots.
 *
 * @package Aether\Router
 */
final class RouteCompiler
{
    /**
     * Compile a RadixTree into a PHP file.
     *
     * @param RadixTree $tree The populated route tree
     * @param string $outputPath Absolute path for the generated file
     */
    public function compile(RadixTree $tree, string $outputPath): void
    {
        $data = $tree->export();
        $exported = var_export($data, true);

        $content = "<?php\n\n";
        $content .= "declare(strict_types=1);\n\n";
        $content .= "/**\n";
        $content .= " * AUTO-GENERATED by Aether Route Compiler.\n";
        $content .= " * DO NOT EDIT — regenerate with `php bin/aether routes:compile`.\n";
        $content .= " *\n";
        $content .= " * Generated: " . date('Y-m-d H:i:s') . "\n";
        $content .= " * Routes: " . $tree->getRouteCount() . "\n";
        $content .= " */\n\n";
        $content .= "return " . $exported . ";\n";

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($outputPath, $content, LOCK_EX);
    }

    /**
     * Load a pre-compiled route tree from a PHP file.
     *
     * @param string $filePath Path to the compiled routes file
     * @return RadixTree Hydrated route tree
     */
    public function load(string $filePath): RadixTree
    {
        if (!is_file($filePath)) {
            throw new \RuntimeException("Compiled routes file not found: {$filePath}");
        }

        /** @var array<string, mixed> $data */
        $data = require $filePath;

        $tree = new RadixTree();
        $tree->import($data);

        return $tree;
    }

    /**
     * Check if compiled routes are stale compared to a source timestamp.
     */
    public function isStale(string $compiledPath, int $sourceTimestamp): bool
    {
        if (!is_file($compiledPath)) {
            return true;
        }

        $compiledTime = filemtime($compiledPath);
        return $compiledTime === false || $compiledTime < $sourceTimestamp;
    }
}
